# Generated by Django 3.0.3 on 2020-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dorman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_part_number', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=200)),
                ('application_summary', models.CharField(max_length=200)),
                ('cross', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fme_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_part_number', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fme_mx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_part_number', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mevotech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_part_number', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='nexcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_part_number', models.CharField(max_length=200)),
                ('oe_part_no', models.CharField(max_length=200)),
                ('am_part_no', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='trw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('part_type', models.CharField(max_length=200)),
                ('application', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
