# Generated by Django 3.0.3 on 2020-10-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nexcat_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('am_part_no', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
